version: '3'


volumes:
  mongodata:
  caddy_data:
  caddy_config:


services:

  fast_api_prod:
    container_name: fast_api_prod
    build: ./app
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 5000
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
    environment:
      - 'MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}'
      - 'MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}'


  mongo_db_prod:
    container_name: mongo_db_prod
    image: mongo:4.2-bionic
    restart: unless-stopped
    volumes:
      - 'mongodata:/data/database'  
    environment:
      - 'MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}'
      - 'MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}'


  caddy_proxy:
    container_name: caddy_proxy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD${UI_DIST_DIR}:/srv
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
 